- resources/profiles/Elegoo/machine/fdm_neptune_4_common.json
Lifted limits to that the printer can actually reach
> Lifted upper limit to actually doable values

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
Modified, grouped settings to fit for n4max 0.4mm nozzle
> tuned n4max 0.4mm nozzle printer settings

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
Changed filament swap to manual, added a lovingly note
> Changed filament swap to manual, added a lovingly note

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
> Offsetted bed area by 5mm each direction to match the 430x430 plate

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.2 nozzle).json
> Update Elegoo Neptune 4 Max (0.2 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
> Updating n4max Extruder Clearance

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.4 nozzle).json
> Update Elegoo Neptune 4 (0.4 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.4 nozzle).json
> fixed missing comma in n4 0.4nozzle

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.2 nozzle).json
> Update Elegoo Neptune 4 (0.2 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.6 nozzle).json
> Update Elegoo Neptune 4 (0.6 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.8 nozzle).json
> Update Elegoo Neptune 4 (0.8 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.4 nozzle).json
> Update Elegoo Neptune 4 Pro (0.4 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.8 nozzle).json
> Lamarc ls n4 0.8 nozzle

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.6 nozzle).json
> add missing octoprint entry

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.2 nozzle).json
> Update Elegoo Neptune 4 Pro (0.2 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.4 nozzle).json
> fixed n4>n4pro naming

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.6 nozzle).json
> Update Elegoo Neptune 4 Pro (0.6 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.8 nozzle).json
> Update Elegoo Neptune 4 Pro (0.8 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
> 4max add print_start

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.6 nozzle).json
> 4max 0.6 update

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.8 nozzle).json
> Update Elegoo Neptune 4 Max (0.8 nozzle).json

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.6 nozzle).json
> fix 0.6 default filament

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.8 nozzle).json
> 4max accels

- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Max (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Plus (0.8 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.2 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.4 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.6 nozzle).json
- resources/profiles/Elegoo/machine/Elegoo Neptune 4 Pro (0.8 nozzle).json
> update wipe settings for all nozzles
